version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/hvdbb
    ports:
      - "3000:3000"
    depends_on:
      - db

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    links:
      - "db"
